#!/bin/bash
# 12-sanoid.sh — Sanoid ZFS snapshot management

DATASETS_CONF="$PROJECT_ROOT/config/datasets.conf"

run() {
    log_section "Sanoid ZFS Snapshot Management"

    # Install Sanoid
    log_cmd "Install EPEL" dnf install -y epel-release
    log_cmd "Install Sanoid" dnf install -y sanoid

    # Read pool name from datasets config
    local pool_name="$ZFS_POOL_NAME"
    if [[ -f "$DATASETS_CONF" ]]; then
        local conf_pool
        conf_pool=$(grep '^ZFS_POOL_NAME=' "$DATASETS_CONF" 2>/dev/null | cut -d= -f2)
        [[ -n "$conf_pool" ]] && pool_name="$conf_pool"
    fi

    # Configure Sanoid
    mkdir -p /etc/sanoid
    cat > /etc/sanoid/sanoid.conf << EOF
# Sanoid configuration for Project TV - Rocky Edition
# Generated by installer on $(date)

[${pool_name}]
  use_template = production
  recursive = yes

[template_production]
  frequently = 0
  hourly = 0
  daily = 60
  weekly = 0
  monthly = 0
  yearly = 0
  autosnap = yes
  autoprune = yes
EOF

    log_info "Sanoid configuration:"
    cat /etc/sanoid/sanoid.conf

    # Create systemd timer
    cat > /etc/systemd/system/sanoid.timer << 'EOF'
[Unit]
Description=Run Sanoid every 15 minutes

[Timer]
OnCalendar=*:0/15
Persistent=true

[Install]
WantedBy=timers.target
EOF

    cat > /etc/systemd/system/sanoid-prune.service << 'EOF'
[Unit]
Description=Sanoid Prune Snapshots
Requires=sanoid.service
After=sanoid.service

[Service]
Type=oneshot
ExecStart=/usr/sbin/sanoid --prune-snapshots --verbose
EOF

    # Enable and start
    log_cmd "Reload systemd" systemctl daemon-reload
    log_cmd "Enable sanoid timer" systemctl enable --now sanoid.timer

    log_success "Sanoid configured with 60-day daily snapshots, running every 15 minutes"
    systemctl status sanoid.timer 2>&1 | head -10
}
