#!/bin/bash
# 13-rsync.sh — Media sync from backup server via rsync + systemd timer

DATASETS_CONF="$PROJECT_ROOT/config/datasets.conf"

run() {
    log_section "Rsync Media Sync Setup"

    if ! ask_yes_no "Do you want to set up rsync from a backup server?"; then
        log_info "Rsync setup skipped"
        return 0
    fi

    # Get backup server details
    local server user remote_path
    server=$(ask_text "Backup server IP or hostname" "$BACKUP_SERVER")
    user=$(ask_text "SSH user on backup server" "$BACKUP_USER")
    remote_path=$(ask_text "Remote base path (e.g. /mnt/backup)" "$BACKUP_PATH")

    # Generate sync script
    local script_dir="/home/${SUDO_USER:-$(whoami)}/scripts"
    mkdir -p "$script_dir"

    local script_file="$script_dir/media-sync.sh"
    cat > "$script_file" << EOF
#!/bin/bash
# media-sync.sh — Pull media from backup server
# Generated by Project TV installer on $(date)

SERVER="${server}"
USER="${user}"
REMOTE_PATH="${remote_path}"

echo "[\$(date)] Starting media sync from \${USER}@\${SERVER}:\${REMOTE_PATH}"

EOF

    # Add rsync commands for each dataset
    if [[ -f "$DATASETS_CONF" ]]; then
        while IFS=: read -r ds_name ds_mount; do
            [[ "$ds_name" =~ ^#.*$ ]] && continue
            [[ -z "$ds_name" ]] && continue
            [[ "$ds_name" =~ ^ZFS_ ]] && continue

            cat >> "$script_file" << EOF
echo "Syncing ${ds_name}..."
rsync -avz --ignore-existing "\${USER}@\${SERVER}:\${REMOTE_PATH}/${ds_name}/" "${ds_mount}/" 2>&1
EOF
        done < "$DATASETS_CONF"
    fi

    cat >> "$script_file" << 'EOF'

echo "[$(date)] Media sync complete"
EOF

    chmod +x "$script_file"
    chown "${SUDO_USER:-$(whoami)}:${SUDO_USER:-$(whoami)}" "$script_file"

    log_info "Sync script created: $script_file"

    # Create systemd service and timer
    cat > /etc/systemd/system/media-sync.service << EOF
[Unit]
Description=Media sync from backup server
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=${SUDO_USER:-$(whoami)}
ExecStart=${script_file}
StandardOutput=journal
StandardError=journal
EOF

    local schedule
    schedule=$(ask_text "Sync schedule (systemd OnCalendar format)" "monthly")

    cat > /etc/systemd/system/media-sync.timer << EOF
[Unit]
Description=Monthly media sync from backup server

[Timer]
OnCalendar=${schedule}
Persistent=true

[Install]
WantedBy=timers.target
EOF

    log_cmd "Reload systemd" systemctl daemon-reload
    log_cmd "Enable media-sync timer" systemctl enable --now media-sync.timer

    log_success "Rsync media sync configured (schedule: $schedule)"
    echo "Script: $script_file"
    echo "Test with: sudo systemctl start media-sync.service"
}
