apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: project-tv
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30300
