apiVersion: v1
kind: Secret
metadata:
  name: tubearchivist-secret
  namespace: project-tv
type: Opaque
stringData:
  ELASTIC_PASSWORD: "CHANGE_ME_ELASTIC_PASSWORD"
  TA_USERNAME: "tubearchivist"
  TA_PASSWORD: "CHANGE_ME_TA_PASSWORD"
