apiVersion: v1
kind: Service
metadata:
  name: tubearchivist
  namespace: project-tv
  labels:
    app: tubearchivist
spec:
  type: NodePort
  selector:
    app: tubearchivist
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30800
