apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: project-tv
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "CHANGE_ME_ROOT_PASSWORD"
  MYSQL_USER: "epgstation"
  MYSQL_PASSWORD: "CHANGE_ME_EPGSTATION_PASSWORD"
  MYSQL_DATABASE: "epgstation"
