apiVersion: v1
kind: Service
metadata:
  name: mirakurun
  namespace: project-tv
  labels:
    app: mirakurun
spec:
  type: NodePort
  selector:
    app: mirakurun
  ports:
  - name: http
    port: 40772
    targetPort: 40772
    nodePort: 30772
  - name: debug
    port: 9229
    targetPort: 9229
